# Generated by Django 5.1.7 on 2025-04-06 07:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("chapter_id", models.AutoField(primary_key=True, serialize=False)),
                ("chapter_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "chapters",
            },
        ),
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "exercise_types",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("school_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "schools",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("source_id", models.AutoField(primary_key=True, serialize=False)),
                ("source_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "sources",
            },
        ),
        migrations.CreateModel(
            name="ExamGroup",
            fields=[
                ("examgroup_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "examgroup_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.chapter",
                    ),
                ),
            ],
            options={
                "db_table": "exam_groups",
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "exercise_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("level", models.IntegerField(default=1)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text1", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.chapter",
                    ),
                ),
                (
                    "exam_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.examgroup",
                    ),
                ),
            ],
            options={
                "db_table": "exercises",
            },
        ),
        migrations.CreateModel(
            name="ExerciseAnalysis",
            fields=[
                ("analysis_id", models.AutoField(primary_key=True, serialize=False)),
                ("analysis_content", models.TextField()),
                ("mark", models.CharField(max_length=20, null=True)),
                ("render_type", models.CharField(max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text1", models.TextField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="core.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "exercise_analysis",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="analysis",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercise_analysis",
                to="core.exerciseanalysis",
            ),
        ),
        migrations.CreateModel(
            name="ExerciseAnswer",
            fields=[
                ("answer_id", models.AutoField(primary_key=True, serialize=False)),
                ("answer_content", models.TextField(blank=True, null=True)),
                ("mark", models.CharField(max_length=100, null=True)),
                ("from_model", models.CharField(blank=True, max_length=20, null=True)),
                ("render_type", models.CharField(max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text1", models.TextField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "exercise_answers",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercise_answer",
                to="core.exerciseanswer",
            ),
        ),
        migrations.CreateModel(
            name="ExerciseImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_link", models.TextField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("stem", "Stem"),
                            ("question", "Question"),
                            ("answer", "Answer"),
                            ("analysis", "Analysis"),
                        ],
                        default="stem",
                        max_length=20,
                    ),
                ),
                ("is_deprecated", models.BooleanField(default=False)),
                ("ocr_result", models.TextField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.exercise"
                    ),
                ),
            ],
            options={
                "db_table": "exercise_images",
            },
        ),
        migrations.CreateModel(
            name="ExerciseStem",
            fields=[
                ("stem_id", models.AutoField(primary_key=True, serialize=False)),
                ("stem_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text1", models.TextField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.exercise"
                    ),
                ),
            ],
            options={
                "db_table": "exercise_stems",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="stem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercise_stem",
                to="core.exercisestem",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.exercisetype",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeTag",
            fields=[
                (
                    "tag_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("tag_name", models.CharField(max_length=100)),
                ("text1", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_tags",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_tags",
            },
        ),
        migrations.CreateModel(
            name="ExerciseKnowledgeTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.exercise"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.knowledgetag",
                    ),
                ),
            ],
            options={
                "db_table": "exercise_knowledge_tags",
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                ("major_id", models.AutoField(primary_key=True, serialize=False)),
                ("major_name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                    ),
                ),
            ],
            options={
                "db_table": "majors",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="major",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.major"
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="major",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.major"
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_order", models.IntegerField(default=0)),
                ("question_stem", models.TextField(blank=True, null=True)),
                ("question_answer", models.TextField()),
                ("question_analysis", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text1", models.TextField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="auth.group"
                    ),
                ),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "from_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("exam_time", models.CharField(blank=True, max_length=20, null=True)),
                ("exam_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "exam_full_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("text1", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="core.category",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "db_table": "exams",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.source",
            ),
        ),
        migrations.CreateModel(
            name="ExerciseFrom",
            fields=[
                (
                    "exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.exercise",
                    ),
                ),
                ("is_official_exercise", models.IntegerField(blank=True, null=True)),
                (
                    "exercise_number",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("section", models.CharField(blank=True, max_length=100, null=True)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("text1", models.TextField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exercise_from",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="exercise_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercise_from",
                to="core.exercisefrom",
            ),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=50)),
                ("can_create", models.BooleanField(default=False)),
                ("can_read", models.BooleanField(default=True)),
                ("can_update", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_permissions",
                "unique_together": {("role", "model_name")},
            },
        ),
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("read", "读取"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("login", "登录"),
                            ("logout", "登出"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=50, null=True)),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_action_logs",
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="user_action_user_id_d2e137_idx",
                    ),
                    models.Index(
                        fields=["action_type", "timestamp"],
                        name="user_action_action__1fcad3_idx",
                    ),
                ],
            },
        ),
    ]
