# Generated by Django 5.1.7 on 2025-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_exerciseimage_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciseanalysis",
            name="from_model",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
