# Generated by Django 5.1.7 on 2025-04-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_question_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseanalysis",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="core.exercise",
            ),
        ),
        migrations.AlterField(
            model_name="exerciseanswer",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="core.exercise",
            ),
        ),
        migrations.AlterField(
            model_name="exerciseanswer",
            name="render_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
