# Generated by Django 5.1.7 on 2025-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_exerciseanalysis_exercise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseanswer",
            name="from_model",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="exerciseanswer",
            name="render_type",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
