# Generated by Django 5.1.7 on 2025-04-05 06:49

import django.db.models.deletion
from django.db import migrations, models


def set_default_category(apps, schema_editor):
    Exam = apps.get_model('core', 'Exam')
    Category = apps.get_model('core', 'Category')
    # 确保 category_id=1 存在，如果不存在则创建一个
    category, created = Category.objects.get_or_create(category_id=1, defaults={'category_name': 'Default Category'})
    # 将所有现有 Exam 的 category 设置为 category_id=1
    Exam.objects.update(category=category)

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_exerciseanswer_from_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="core.category",
                
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_category, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(
               
                on_delete=models.CASCADE,
                related_name='exams',
                to='core.Category',
            ),
        ),
    ]
